#!/usr/bin/env .venv/bin/python

import pyautogui
from collections import namedtuple
# from datetime import datetime, timezone
# from zoneinfo import ZoneInfo

# def now_time(countdown: bool=False):
#     today = datetime.now(timezone.utc).astimezone(ZoneInfo("Asia/Manila"))
#     timer_start = (60 - today.second)
#     return today if not countdown else timer_start

LOG_LEVEL = ""#DEBUG"
BREAKOUT_FILE = "breakout_data.json"
DATA_FILE = "previous_data.json"
HELPSLOT_DATA_FILE = "previous_helpslot_data.json"
TREND_FILE = "trend_data.json"

# === Screen Dimensions ===
SCREEN_WIDTH, SCREEN_HEIGHT = pyautogui.size()
HALF_WIDTH = SCREEN_WIDTH // 2

# == Single Slot Size
SCREEN_POS = {
    "center_x": SCREEN_WIDTH // 2,
    "center_y": SCREEN_HEIGHT // 2,
    "right_x": SCREEN_WIDTH - 1,
    "bottom_y": SCREEN_HEIGHT - 1
}

# == Dual Slot Sizes
LEFT_SLOT_POS = {
    "center_x": HALF_WIDTH // 2,
    "center_y": SCREEN_HEIGHT // 2
}

RIGHT_SLOT_POS = {
    "center_x": HALF_WIDTH + (HALF_WIDTH // 2),
    "center_y": SCREEN_HEIGHT // 2
}

# === Voice and Sound Settings ===
PING = "/System/Library/Sounds/Ping.aiff"
VOICES = {
    "Samantha": "Samantha",
    "Trinoids": "Trinoids",
    "Kanya": "Kanya",
    "Karen": "Karen",
    "Kathy": "Kathy",
    "Nora": "Nora",
}

# === Default Timeouts ===
# HOLD_DELAY_RANGE = (2.6, 3.4)  # Used with random.uniform(*HOLD_DELAY_RANGE)
HOLD_DELAY_RANGE = (1.5, 3)  # Used with random.uniform(*HOLD_DELAY_RANGE)
# SPIN_DELAY_RANGE = (2.8, 3.5)  # Used with random.uniform(*SPIN_DELAY_RANGE)
SPIN_DELAY_RANGE = (1, 2)  # Used with random.uniform(*SPIN_DELAY_RANGE)
TIMEOUT_DELAY_RANGE = (0.5, 2.5)  # Used with random.uniform(*TIMEOUT_DELAY_RANGE)

# COLORS
RED='\033[31m'; GRE='\033[32m'; YEL='\033[33m'
BLU='\033[34m'; MAG='\033[35m'; CYN='\033[36m'
LGRY='\033[37m'; DGRY='\033[90m'; LRED='\033[91m'
LGRE='\033[92m'; LYEL='\033[93m'; LBLU='\033[94m'
LMAG='\033[95m'; LCYN='\033[96m'; WHTE='\033[97m'
BLNK='\033[5m'; NBLNK='\033[25m'; RES='\033[0m'
BLRED = '\033[1;91m'; BLGRE = '\033[1;92m'; BLYEL = '\033[1;93m'
BRED = '\033[1;91m'; BMAG = '\033[1;35m'; BYEL = '\033[1;33m'
BBLU = '\033[1;34m'; BGRE ='\033[1;32m'; BCYN = '\033[1;36m' 
BWHTE = '\033[1;97m'; BDGRY = '\033[1;90m'; BLGRY = '\033[1;37m'; 
BLMAG = '\033[1;95m'; BLBLU = '\033[1;94m'; BLCYN = '\033[1;96m'
CLEAR = '\033[H\033[J'

GameConfig = namedtuple("GameConfig", [
    "spin_btn", "auto_spin", "turbo", "feature",
    "auto_play_menu", "widescreen", "provider"
])

GAME_CONFIGS = {
    # Jili
    "10 Sparkling Crown": GameConfig(False, True, True, None, False, True, "JILI"),
    "3 Charge Buffalo": GameConfig(False, True, True, None, False, True, "JILI"),
    "3 Coin Treasures": GameConfig(False, True, True, None, False, True, "JILI"),
    "3 Coin Treasures 2": GameConfig(False, True, True, None, False, True, "JILI"),
    "3 Coin Wild Horse": GameConfig(False, True, True, None, False, True, "JILI"),
    "3 LUCKY LION": GameConfig(False, True, True, None, False, True, "JILI"),
    "3 Lucky Piggy": GameConfig(False, True, True, None, False, True, "JILI"),
    "3 Pot Dragons": GameConfig(False, True, True, None, False, True, "JILI"),
    "3 Witch's Lamp": GameConfig(False, True, True, None, False, True, "JILI"),
    "40 Sparkling Crown": GameConfig(False, True, True, None, False, True, "JILI"),
    "7up7down": GameConfig(False, True, True, None, False, True, "JILI"),
    "Agent Ace": GameConfig(False, True, True, None, False, True, "JILI"),
    "Ali Baba": GameConfig(False, True, True, None, False, True, "JILI"),
    "Arena Fighter": GameConfig(False, True, True, None, False, True, "JILI"),
    "Aztec Priestess": GameConfig(False, True, True, None, False, True, "JILI"),
    "Baccarat": GameConfig(False, True, True, None, False, True, "JILI"),
    "Bangla Beauty": GameConfig(False, True, True, None, False, True, "JILI"),
    "Bao boon chin": GameConfig(False, True, True, None, False, True, "JILI"),
    "Big Small": GameConfig(False, True, True, None, False, True, "JILI"),
    "Bikini Lady": GameConfig(False, True, True, None, False, True, "JILI"),
    "Bingo Adventure": GameConfig(False, True, True, None, False, True, "JILI"),
    "Bingo Carnaval": GameConfig(False, True, True, None, False, True, "JILI"),
    "Bone Fortune": GameConfig(False, True, True, None, False, True, "JILI"),
    "Bonus Hunter": GameConfig(False, True, True, None, False, False, "JILI"),
    "Book of Gold": GameConfig(False, True, True, None, False, True, "JILI"),
    "Boxing Extravaganza": GameConfig(False, True, True, None, False, True, "JILI"),
    "Boxing King": GameConfig(False, True, True, None, False, True, "JILI"),
    "Bubble Beauty": GameConfig(False, True, True, None, False, True, "JILI"),
    "Calaca Bingo": GameConfig(False, True, True, None, False, True, "JILI"),
    "Candy Baby": GameConfig(False, True, True, None, False, False, "JILI"),
    "Charge Buffalo": GameConfig(False, True, True, None, False, True, "JILI"),
    "Charge Buffalo Ascent": GameConfig(False, True, True, None, False, True, "JILI"),
    "Chin Shi Huang": GameConfig(False, True, True, None, False, True, "JILI"),
    "Circus Joker 4096": GameConfig(False, True, True, None, False, True, "JILI"),
    "Clover Coins 3x3": GameConfig(False, True, True, None, False, True, "JILI"),
    "Coin Infinity Surge Reel": GameConfig(False, True, True, None, False, True, "JILI"),
    "Coin Tree": GameConfig(False, True, True, None, False, True, "JILI"),
    "Crash Bonus": GameConfig(False, True, True, None, False, True, "JILI"),
    "Crash Cricket": GameConfig(False, True, True, None, False, True, "JILI"),
    "Crash Goal": GameConfig(False, True, True, None, False, True, "JILI"),
    "Crash Touchdown": GameConfig(False, True, True, None, False, True, "JILI"),
    "Crazy FaFaFa": GameConfig(False, True, True, None, False, True, "JILI"),
    "Crazy Hunter": GameConfig(False, True, True, None, False, True, "JILI"),
    "Crazy Hunter 2": GameConfig(False, True, True, None, False, True, "JILI"),
    "Crazy Pusher": GameConfig(False, True, True, None, False, True, "JILI"),
    "Crazy777": GameConfig(False, True, True, None, False, True, "JILI"),
    "Cricket King 18": GameConfig(False, True, True, None, False, True, "JILI"),
    "Cricket Sah 75": GameConfig(False, True, True, None, False, True, "JILI"),
    "Dabanggg": GameConfig(False, True, True, None, False, True, "JILI"),
    "Devil Fire": GameConfig(False, True, True, None, False, True, "JILI"),
    "Devil Fire 2": GameConfig(False, True, True, None, False, True, "JILI"),
    "Diamond Party": GameConfig(False, True, True, None, False, True, "JILI"),
    "DiamondParty": GameConfig(False, True, True, None, False, True, "JILI"),
    "Dragon Treasure": GameConfig(False, True, True, None, False, True, "JILI"),
    "Egypt's Glow": GameConfig(False, True, True, None, False, True, "JILI"),
    "Elf Bingo": GameConfig(False, True, True, None, False, True, "JILI"),
    "European Roulette": GameConfig(False, True, True, None, False, True, "JILI"),
    "Fa Fa Fa": GameConfig(False, True, True, None, False, True, "JILI"),
    "Fengshen": GameConfig(False, True, True, None, False, True, "JILI"),
    "Fish Prawn Crab": GameConfig(False, True, True, None, False, True, "JILI"),
    "Fortune Bingo": GameConfig(False, True, True, None, False, True, "JILI"),
    "Fortune Coins": GameConfig(False, True, True, None, False, True, "JILI"),
    "Fortune Gems": GameConfig(False, True, True, None, False, True, "JILI"),
    "Fortune Gems 2": GameConfig(False, True, True, None, False, True, "JILI"),
    "Fortune Gems 3": GameConfig(False, True, True, None, False, True, "JILI"),
    "Fortune Gems Scratch": GameConfig(False, True, True, None, False, True, "JILI"),
    "Fortune Monkey": GameConfig(False, True, True, None, False, True, "JILI"),
    "Fortune Pig": GameConfig(False, True, True, None, False, True, "JILI"),
    "Fortune Tree": GameConfig(False, True, True, None, False, True, "JILI"),
    "FortunePig": GameConfig(False, True, True, None, False, True, "JILI"),
    "Fruity Wheel": GameConfig(False, True, True, None, False, True, "JILI"),
    "Gem Party": GameConfig(False, True, True, None, False, True, "JILI"),
    "Go For Champion": GameConfig(False, True, True, None, False, True, "JILI"),
    "Go Goal Bingo": GameConfig(False, True, True, None, False, True, "JILI"),
    "God Of Martial": GameConfig(False, True, True, None, False, True, "JILI"),
    "Gold Rush": GameConfig(False, True, True, None, False, True, "JILI"),
    "Golden Bank": GameConfig(False, True, True, None, False, True, "JILI"),
    "Golden Bank 2": GameConfig(False, True, True, None, False, True, "JILI"),
    "Golden Empire": GameConfig(False, True, True, None, False, True, "JILI"),
    "Golden Empire 2": GameConfig(False, True, True, None, False, True, "JILI"),
    "Golden Joker": GameConfig(False, True, True, None, False, True, "JILI"),
    "Golden Land": GameConfig(False, True, True, None, False, True, "JILI"),
    "Golden Queen": GameConfig(False, True, True, None, False, True, "JILI"),
    "Golden Temple": GameConfig(False, True, True, None, False, True, "JILI"),
    "Golden Treasure Lightning": GameConfig(False, True, True, None, False, True, "JILI"),
    "Happy Taxi": GameConfig(False, True, True, None, False, True, "JILI"),
    "Hawaii Beauty": GameConfig(False, True, True, None, False, True, "JILI"),
    "Hilo": GameConfig(False, True, True, None, False, True, "JILI"),
    "Hot Chilli": GameConfig(False, True, True, None, False, True, "JILI"),
    "Hyper Burst": GameConfig(False, True, True, None, False, True, "JILI"),
    "Jili Caishen": GameConfig(False, True, True, None, False, True, "JILI"),
    "Jackpot Bingo": GameConfig(False, True, True, None, False, True, "JILI"),
    "Jackpot Joker": GameConfig(False, True, True, None, False, True, "JILI"),
    "Jhandi Munda": GameConfig(False, True, True, None, False, True, "JILI"),
    "Jogo Do Bicho": GameConfig(False, True, True, None, False, True, "JILI"),
    "Joker Coins": GameConfig(False, True, True, None, False, True, "JILI"),
    "Journey West M": GameConfig(False, True, True, None, False, True, "JILI"),
    "Jungle King": GameConfig(False, True, True, None, False, True, "JILI"),
    "Keno": GameConfig(False, True, True, None, False, True, "JILI"),
    "Keno Bonus Number": GameConfig(False, True, True, None, False, True, "JILI"),
    "Keno Super Chance": GameConfig(False, True, True, None, False, True, "JILI"),
    "King Arthur": GameConfig(False, True, True, None, False, True, "JILI"),
    "Legacy of Egypt": GameConfig(False, True, True, None, False, True, "JILI"),
    "Lucky Ball": GameConfig(False, True, True, None, False, True, "JILI"),
    "Lucky Bingo": GameConfig(False, True, True, None, False, True, "JILI"),
    "Lucky Coming": GameConfig(False, True, True, None, False, True, "JILI"),
    "Lucky Doggy": GameConfig(False, True, True, None, False, True, "JILI"),
    "Lucky Goldbricks": GameConfig(False, True, True, None, False, True, "JILI"),
    "Lucky Jaguar": GameConfig(False, True, True, None, False, True, "JILI"),
    "Magic Lamp": GameConfig(False, True, True, None, False, True, "JILI"),
    "Magic Lamp Bingo": GameConfig(False, True, True, None, False, True, "JILI"),
    "Master Tiger": GameConfig(False, True, True, None, False, True, "JILI"),
    "Mayan Empire": GameConfig(False, True, True, None, False, True, "JILI"),
    # "Medusa": GameConfig(False, True, True, None, False, True, "JILI"), Conflict Key same name
    "Mega Ace": GameConfig(False, True, True, None, False, False, "JILI"),
    "Mines Gold": GameConfig(False, True, True, None, False, True, "JILI"),
    "Mines Grand": GameConfig(False, True, True, None, False, True, "JILI"),
    "Money Coming": GameConfig(False, True, True, None, False, True, "JILI"),
    "Money Coming 2": GameConfig(False, True, True, None, False, True, "JILI"),
    "Money Coming Expand Bets": GameConfig(False, True, True, None, False, True, "JILI"),
    "Money Pot": GameConfig(False, True, True, None, False, True, "JILI"),
    "Money Pot Deluxe": GameConfig(False, True, True, None, False, True, "JILI"),
    "Monkey Party": GameConfig(False, True, True, None, False, True, "JILI"),
    "Neko Fortune": GameConfig(False, True, True, None, False, True, "JILI"),
    "Night City": GameConfig(False, True, True, None, False, True, "JILI"),
    "Nightfall Hunting": GameConfig(False, True, True, None, False, True, "JILI"),
    "Number King": GameConfig(False, True, True, None, False, True, "JILI"),
    "Pappu": GameConfig(False, True, True, None, False, True, "JILI"),
    "Party Night": GameConfig(False, True, True, None, False, True, "JILI"),
    "Party Star": GameConfig(False, True, True, None, False, False, "JILI"),
    "Pharaoh Treasure": GameConfig(False, True, True, None, False, True, "JILI"),
    "Pirate Queen": GameConfig(False, True, True, None, False, True, "JILI"),
    "Pirate Queen 2": GameConfig(False, True, True, None, False, True, "JILI"),
    "Plinko": GameConfig(False, True, True, None, False, True, "JILI"),
    "Poker King": GameConfig(False, True, True, None, False, True, "JILI"),
    "Poseidon": GameConfig(False, True, True, None, False, True, "JILI"),
    "Potion Wizard": GameConfig(False, True, True, None, False, True, "JILI"),
    "Roma X Deluxe": GameConfig(False, True, True, None, False, True, "JILI"),
    "RomaX": GameConfig(False, True, True, None, False, True, "JILI"),
    "Safari King": GameConfig(False, True, True, None, False, True, "JILI"),
    "Safari Mystery": GameConfig(False, True, True, None, False, True, "JILI"),
    "Samba": GameConfig(False, True, True, None, False, True, "JILI"),
    "Secret Treasure": GameConfig(False, True, True, None, False, True, "JILI"),
    "Seven Seven Seven": GameConfig(False, True, True, None, False, True, "JILI"),
    "SevenSevenSeven": GameConfig(False, True, True, None, False, True, "JILI"),
    "Shanghai Beauty": GameConfig(False, True, True, None, False, True, "JILI"),
    "Shōgun": GameConfig(False, True, True, None, False, True, "JILI"),
    "Sic Bo": GameConfig(False, True, True, None, False, True, "JILI"),
    "Sin City": GameConfig(False, True, True, None, False, True, "JILI"),
    "Speed Baccarat": GameConfig(False, True, True, None, False, True, "JILI"),
    "Super Ace": GameConfig(False, True, True, None, False, False, "JILI"),
    "Super Ace Deluxe": GameConfig(False, True, True, None, False, False, "JILI"),
    "Super Ace II": GameConfig(False, True, True, None, False, False, "JILI"),
    "Super Ace Joker": GameConfig(False, True, True, None, False, False, "JILI"),
    "Super Ace Scratch": GameConfig(False, True, True, None, False, True, "JILI"),
    "Super Bingo": GameConfig(False, True, True, None, False, True, "JILI"),
    "Super E-Sabong": GameConfig(False, True, True, None, False, True, "JILI"),
    "Super Rich": GameConfig(False, True, True, None, False, True, "JILI"),
    "Sweet Land": GameConfig(False, True, True, None, False, True, "JILI"),
    "Twin Wins": GameConfig(False, True, True, None, False, True, "JILI"),
    "The Pig House": GameConfig(False, True, True, None, False, True, "JILI"),
    "Thor X": GameConfig(False, True, True, None, False, True, "JILI"),
    "Treasure Quest": GameConfig(False, True, True, None, False, True, "JILI"),
    "Trial of Phoenix": GameConfig(False, True, True, None, False, True, "JILI"),
    "Video Poker": GameConfig(False, True, True, None, False, True, "JILI"),
    "War Of Dragons": GameConfig(False, True, True, None, False, True, "JILI"),
    "West Hunger Bingo": GameConfig(False, True, True, None, False, True, "JILI"),
    "Wheel": GameConfig(False, True, True, None, False, True, "JILI"),
    "Wild Ace": GameConfig(False, True, True, None, False, False, "JILI"),
    "Wild Racer": GameConfig(False, True, True, None, False, True, "JILI"),
    "Win Drop": GameConfig(False, True, True, None, False, True, "JILI"),
    "Witches Night": GameConfig(False, True, True, None, False, True, "JILI"),
    "World Cup": GameConfig(False, True, True, None, False, True, "JILI"),
    "Xi Yang Yang": GameConfig(False, True, True, None, False, True, "JILI"),
    "XiYangYang": GameConfig(False, True, True, None, False, True, "JILI"),
    "Zeus": GameConfig(False, True, True, None, False, True, "JILI"),
    # Pocket Game Soft
    "Alchemy Gold": GameConfig(False, True, True, None, False, False, "PG"),
    "Anubis Wrath": GameConfig(False, True, True, None, False, False, "PG"),
    "Asgardian Rising": GameConfig(False, True, True, None, False, False, "PG"),
    "Bakery Bonanza": GameConfig(False, True, True, None, False, False, "PG"),
    "Bali Vacation": GameConfig(False, True, True, None, False, False, "PG"),
    "Battleground Royale": GameConfig(False, True, True, None, False, False, "PG"),
    "Bikini Paradise": GameConfig(False, True, True, None, False, False, "PG"),
    "Buffalo Win": GameConfig(False, True, True, None, False, False, "PG"),
    "Butterfly Blossom": GameConfig(False, True, True, None, False, False, "PG"),
    "Caishen Wins": GameConfig(False, True, True, None, False, False, "PG"),
    "Candy Bonanza": GameConfig(False, True, True, None, False, False, "PG"),
    "Candy Burst": GameConfig(False, True, True, None, False, False, "PG"),
    "Captain's Bounty": GameConfig(False, True, True, None, False, False, "PG"),
    "Cash Mania": GameConfig(False, True, True, None, False, False, "PG"),
    "Chicky Run": GameConfig(False, True, True, None, False, False, "PG"),
    "Chocolate Deluxe": GameConfig(False, True, True, None, False, False, "PG"),
    "Circus Delight": GameConfig(False, True, True, None, False, False, "PG"),
    "Cocktail Nights": GameConfig(False, True, True, None, False, False, "PG"),
    "Cruise Royale": GameConfig(False, True, True, None, False, False, "PG"),
    "Crypto Gold": GameConfig(False, True, True, None, False, False, "PG"),
    "Dead Man's Riches": GameConfig(False, True, True, None, False, False, "PG"),
    "Destiny of Sun & Moon": GameConfig(False, True, True, None, False, False, "PG"),
    "Diner Delights": GameConfig(False, True, True, None, False, False, "PG"),
    "Diner Frenzy Spins": GameConfig(False, True, True, None, False, False, "PG"),
    "Doomsday Rampage": GameConfig(False, True, True, None, False, False, "PG"),
    "Double Fortune": GameConfig(False, True, True, None, False, False, "PG"),
    "Dragon Hatch": GameConfig(False, True, True, None, False, False, "PG"),
    "Dragon Hatch 2": GameConfig(False, True, True, None, False, False, "PG"),
    "Dragon Legend": GameConfig(False, True, True, None, False, False, "PG"),
    "Dragon Tiger Luck": GameConfig(False, True, True, None, False, False, "PG"),
    "Dragon's Treasure Quest": GameConfig(False, True, True, None, False, False, "PG"),
    "Dreams of Macau": GameConfig(False, True, True, None, False, False, "PG"),
    "Egypt's Book of Mystery": GameConfig(False, True, True, None, False, False, "PG"),
    "Emoji Riches": GameConfig(False, True, True, None, False, False, "PG"),
    "Emperor's Favour": GameConfig(False, True, True, None, False, False, "PG"),
    "Flirting Scholar": GameConfig(False, True, True, None, False, False, "PG"),
    "Forge of Wealth": GameConfig(False, True, True, None, False, False, "PG"),
    "Fortune Dragon": GameConfig(False, True, True, None, False, False, "PG"),
    "Fortune Gods": GameConfig(False, True, True, None, False, False, "PG"),
    "Fortune Mouse": GameConfig(False, True, True, None, False, False, "PG"),
    "Fortune Ox": GameConfig(False, True, True, None, False, False, "PG"),
    "Fortune Rabbit": GameConfig(False, True, True, None, False, False, "PG"),
    "Fortune Snake": GameConfig(False, True, True, None, False, False, "PG"),
    "Fortune Tiger": GameConfig(False, True, True, None, False, False, "PG"),
    "Fruit Candy": GameConfig(False, True, True, None, False, False, "PG"),
    "Fruity Candy": GameConfig(False, True, True, None, False, False, "PG"),
    "Futebol Fever": GameConfig(False, True, True, None, False, False, "PG"),
    "Galactic Gems": GameConfig(False, True, True, None, False, False, "PG"),
    "Galaxy Miner": GameConfig(False, True, True, None, False, False, "PG"),
    "Ganesha Fortune": GameConfig(False, True, True, None, False, False, "PG"),
    "Ganesha Gold": GameConfig(False, True, True, None, False, False, "PG"),
    "Garuda Gems": GameConfig(False, True, True, None, False, False, "PG"),
    "Geisha's Revenge": GameConfig(False, True, True, None, False, False, "PG"),
    "Gem Saviour": GameConfig(False, True, True, None, False, False, "PG"),
    "Gem Saviour Conquest": GameConfig(False, True, True, None, False, False, "PG"),
    "Gem Saviour Sword": GameConfig(False, True, True, None, False, False, "PG"),
    "Gemstones Gold": GameConfig(False, True, True, None, False, False, "PG"),
    "Genie's 3 Wishes": GameConfig(False, True, True, None, False, False, "PG"),
    "Gladiator's Glory": GameConfig(False, True, True, None, False, False, "PG"),
    "Graffiti Rush": GameConfig(False, True, True, None, False, False, "PG"),
    "Grimms' Bounty: Hansel & Gretel": GameConfig(False, True, True, None, False, False, "PG"),
    "Guardians of Ice and Fire": GameConfig(False, True, True, None, False, False, "PG"),
    "Hawaiian Tiki": GameConfig(False, True, True, None, False, False, "PG"),
    "Heist Stakes": GameConfig(False, True, True, None, False, False, "PG"),
    "Heist of Stakes": GameConfig(False, True, True, None, False, False, "PG"),
    "Hip Hop Panda": GameConfig(False, True, True, None, False, False, "PG"),
    "Honey Trap of Diao Chan": GameConfig(False, True, True, None, False, False, "PG"),
    "Hood vs Wolf": GameConfig(False, True, True, None, False, False, "PG"),
    "Hotpot": GameConfig(False, True, True, None, False, False, "PG"),
    "Incan Wonders": GameConfig(False, True, True, None, False, False, "PG"),
    "Jack Frost's Winter": GameConfig(False, True, True, None, False, False, "PG"),
    "Jack the Giant Hunter": GameConfig(False, True, True, None, False, False, "PG"),
    "Jewels of Prosperity": GameConfig(False, True, True, None, False, False, "PG"),
    "Journey to the Wealth": GameConfig(False, True, True, None, False, False, "PG"),
    "Jungle Delight": GameConfig(False, True, True, None, False, False, "PG"),
    "Jurassic Kingdom": GameConfig(False, True, True, None, False, False, "PG"),
    "Knockout Riches": GameConfig(False, True, True, None, False, False, "PG"),
    "Legend of Hou Yi": GameConfig(False, True, True, None, False, False, "PG"),
    "Legend of Perseus": GameConfig(False, True, True, None, False, False, "PG"),
    "Legendary Monkey King": GameConfig(False, True, True, None, False, False, "PG"),
    "Leprechaun Riches": GameConfig(False, True, True, None, False, False, "PG"),
    "Lucky Clover Lady": GameConfig(False, True, True, None, False, False, "PG"),
    "Lucky Clover Riches": GameConfig(False, True, True, None, False, False, "PG"),
    "Lucky Neko": GameConfig(False, True, True, None, False, False, "PG"),
    "Lucky Piggy": GameConfig(False, True, True, None, False, False, "PG"),
    "Mafia Mayhem": GameConfig(False, True, True, None, False, False, "PG"),
    "Mahjong Ways": GameConfig(False, True, True, None, False, False, "PG"),
    "Mahjong Ways 2": GameConfig(False, True, True, None, False, False, "PG"),
    "Majestic Treasures": GameConfig(False, True, True, None, False, False, "PG"),
    "Mask Carnival": GameConfig(False, True, True, None, False, False, "PG"),
    "Medusa": GameConfig(False, True, True, None, False, False, "PG"),
    "Medusa II": GameConfig(False, True, True, None, False, False, "PG"),
    "Mermaid Riches": GameConfig(False, True, True, None, False, False, "PG"),
    "Midas Fortune": GameConfig(False, True, True, None, False, False, "PG"),
    "Mr. Hallow-Win": GameConfig(False, True, True, None, False, False, "PG"),
    "Mr. Treasure’s Fortune": GameConfig(False, True, True, None, False, False, "PG"),
    "Muay Thai Champion": GameConfig(False, True, True, None, False, False, "PG"),
    "Museum Mystery": GameConfig(False, True, True, None, False, False, "PG"),
    "Mystic Potion": GameConfig(False, True, True, None, False, False, "PG"),
    "Mystical Spirits": GameConfig(False, True, True, None, False, False, "PG"),
    "Ninja Raccoon Frenzy": GameConfig(False, True, True, None, False, False, "PG"),
    "Ninja Racoon Frenzy": GameConfig(False, True, True, None, False, False, "PG"),
    "Ninja vs Samurai": GameConfig(False, True, True, None, False, False, "PG"),
    "Oishi Delights": GameConfig(False, True, True, None, False, False, "PG"),
    "Opera Dynasty": GameConfig(False, True, True, None, False, False, "PG"),
    "Oriental Prosperity": GameConfig(False, True, True, None, False, False, "PG"),
    "Phoenix Rises": GameConfig(False, True, True, None, False, False, "PG"),
    "Piggy Gold": GameConfig(False, True, True, None, False, False, "PG"),
    "Pinata Wins": GameConfig(False, True, True, None, False, False, "PG"),
    "Plushie Frenzy": GameConfig(False, True, True, None, False, False, "PG"),
    "Prosperity Fortune Tree": GameConfig(False, True, True, None, False, False, "PG"),
    "Prosperity Lion": GameConfig(False, True, True, None, False, False, "PG"),
    "Queen of Bounty": GameConfig(False, True, True, None, False, False, "PG"),
    "Raider Jane's Crypt of Fortune": GameConfig(False, True, True, None, False, False, "PG"),
    "Rave Party Fever": GameConfig(False, True, True, None, False, False, "PG"),
    "Reel Love": GameConfig(False, True, True, None, False, False, "PG"),
    "Rio Fantasia": GameConfig(False, True, True, None, False, False, "PG"),
    "Rise of Apollo": GameConfig(False, True, True, None, False, False, "PG"),
    "Rooster Rumble": GameConfig(False, True, True, None, False, False, "PG"),
    "Safari Wilds": GameConfig(False, True, True, None, False, False, "PG"),
    "Santa's Gift Rush": GameConfig(False, True, True, None, False, False, "PG"),
    "Secret of Cleopatra": GameConfig(False, True, True, None, False, False, "PG"),
    "Secrets of Cleopatra": GameConfig(False, True, True, None, False, False, "PG"),
    "Shaolin Soccer": GameConfig(False, True, True, None, False, False, "PG"),
    "Shark Bounty": GameConfig(False, True, True, None, False, False, "PG"),
    "Songkran Splash": GameConfig(False, True, True, None, False, False, "PG"),
    "Speed Winner": GameConfig(False, True, True, None, False, False, "PG"),
    "Spirited Wonders": GameConfig(False, True, True, None, False, False, "PG"),
    "Super Golf Drive": GameConfig(False, True, True, None, False, False, "PG"),
    "Supermarket Spree": GameConfig(False, True, True, None, False, False, "PG"),
    "Symbols of Egypt": GameConfig(False, True, True, None, False, False, "PG"),
    "Thai River Wonders": GameConfig(False, True, True, None, False, False, "PG"),
    "The Great Icescape": GameConfig(False, True, True, None, False, False, "PG"),
    "The Queen's Banquet": GameConfig(False, True, True, None, False, False, "PG"),
    "Three Crazy Piggies": GameConfig(False, True, True, None, False, False, "PG"),
    "Totem Wonders": GameConfig(False, True, True, None, False, False, "PG"),
    "Treasures of Aztec": GameConfig(False, True, True, None, False, False, "PG"),
    "Tree of Fortune": GameConfig(False, True, True, None, False, False, "PG"),
    "Tsar Treasures": GameConfig(False, True, True, None, False, False, "PG"),
    "Ultimate Striker": GameConfig(False, True, True, None, False, False, "PG"),
    "Vampire's Charm": GameConfig(False, True, True, None, False, False, "PG"),
    "Ways of Qilin": GameConfig(False, True, True, None, False, False, "PG"),
    "Ways of the Qilin": GameConfig(False, True, True, None, False, False, "PG"),
    "Werewolf's Hunt": GameConfig(False, True, True, None, False, False, "PG"),
    "Wild Ape #3258": GameConfig(False, True, True, None, False, False, "PG"),
    "Wild Ape#3258": GameConfig(False, True, True, None, False, False, "PG"),
    "Wild Bandito": GameConfig(False, True, True, None, False, False, "PG"),
    "Wild Bounty Showdown": GameConfig(False, True, True, None, False, False, "PG"),
    "Wild Coaster": GameConfig(False, True, True, None, False, False, "PG"),
    "Wild Fireworks": GameConfig(False, True, True, None, False, False, "PG"),
    "Wild Heist Cashout": GameConfig(False, True, True, None, False, False, "PG"),
    "Win Win Fish Prawn Crab": GameConfig(False, True, True, None, False, False, "PG"),
    "Win Win Won": GameConfig(False, True, True, None, False, False, "PG"),
    "Wings of Iguazu": GameConfig(False, True, True, None, False, False, "PG"),
    "Yakuza Honor": GameConfig(False, True, True, None, False, False, "PG"),
    "Zombie Outbreak": GameConfig(False, True, True, None, False, False, "PG"),
    # Fa Chai
    "Animal Racing": GameConfig(True, True, True, None, False, False, "FC"),
    "Boxing Riches": GameConfig(True, True, True, None, False, False, "FC"),
    "Chilihuahua": GameConfig(True, True, True, None, False, False, "FC"),
    "Chinese New Year": GameConfig(True, True, True, None, False, False, "FC"),
    "Chinese New Year 2": GameConfig(True, True, True, None, False, False, "FC"),
    "Cowboys": GameConfig(True, True, True, None, False, False, "FC"),
    "Crazy Buffalo": GameConfig(True, True, True, None, False, False, "FC"),
    "Chinese New Year Moreways": GameConfig(True, True, True, None, False, False, "FC"),
    "Circus Dozer": GameConfig(True, True, True, None, False, False, "FC"),
    "Da Le Men": GameConfig(True, True, True, None, False, False, "FC"),
    "Egypt Bonanza": GameConfig(True, True, True, None, False, False, "FC"),
    "Fortune Egg": GameConfig(True, True, True, None, False, False, "FC"),
    "Fortune Koi": GameConfig(True, True, True, None, False, False, "FC"),
    "Fortune Sheep": GameConfig(True, True, True, None, False, False, "FC"),
    "Fa Chai Dozer": GameConfig(True, True, True, None, False, False, "FC"),
    "Fortune Goddess": GameConfig(True, True, True, None, False, False, "FC"),
    "Fortune Money Boom": GameConfig(True, True, True, None, False, False, "FC"),
    "Glory of Rome": GameConfig(True, True, True, None, False, False, "FC"),
    "Gold Rush": GameConfig(True, True, True, None, False, False, "FC"),
    "Golden Genie": GameConfig(True, True, True, None, False, False, "FC"),
    "Golden Panther": GameConfig(True, True, True, None, False, False, "FC"),
    "Grand Blue": GameConfig(True, True, True, None, False, False, "FC"),
    "Go Go Rise": GameConfig(True, True, True, None, False, False, "FC"),
    "Gods Grant Fortune": GameConfig(True, True, True, None, False, False, "FC"),
    "Happy Duo Bao": GameConfig(True, True, True, None, False, False, "FC"),
    "Hot Pot Party": GameConfig(True, True, True, None, False, False, "FC"),
    "Jungle Bang Bang": GameConfig(True, True, True, None, False, False, "FC"),
    "Legend of Inca": GameConfig(True, True, True, None, False, False, "FC"),
    "Lucky Fortunes": GameConfig(True, True, True, None, False, False, "FC"),
    "Lucky Fortunes 3x3": GameConfig(True, True, True, None, False, False, "FC"),
    "Luxury The Golden Panther": GameConfig(True, True, True, None, False, False, "FC"),
    "Lightning Bomb": GameConfig(True, True, True, None, False, False, "FC"),
    "Luxury Golden Panther": GameConfig(True, True, True, None, False, False, "FC"),
    "Magic Beans": GameConfig(True, True, True, None, False, False, "FC"),
    "Merge Magic": GameConfig(True, True, True, None, False, False, "FC"),
    "Mines": GameConfig(True, True, True, None, False, False, "FC"),
    "Money Tree Dozer": GameConfig(True, True, True, None, False, False, "FC"),
    "Night Market": GameConfig(True, True, True, None, False, False, "FC"),
    "Night Market 2": GameConfig(True, True, True, None, False, False, "FC"),
    "Panda Dragon Boat": GameConfig(True, True, True, None, False, False, "FC"),
    "Phoenix Fever": GameConfig(True, True, True, None, False, False, "FC"),
    "Pong Pong Hu": GameConfig(True, True, True, None, False, False, "FC"),
    "Poker Win": GameConfig(True, True, True, None, False, False, "FC"),
    "Queen of Inca": GameConfig(True, True, True, None, False, False, "FC"),
    "Rich Man": GameConfig(True, True, True, None, False, False, "FC"),
    "Robin Hood": GameConfig(True, True, True, None, False, False, "FC"),
    "Roma Gladiatrix": GameConfig(True, True, True, None, False, False, "FC"),
    "Sugar Bang Bang": GameConfig(True, True, True, None, False, False, "FC"),
    "Sugar Bang Bang 2": GameConfig(True, True, True, None, False, False, "FC"),
    "Super Color Game": GameConfig(True, True, True, None, False, False, "FC"),
    "Super Elements": GameConfig(True, True, True, None, False, False, "FC"),
    "The The Golden Panther": GameConfig(True, True, True, None, False, False, "FC"),
    "Three Little Pigs": GameConfig(True, True, True, None, False, False, "FC"),
    "Treasure Cruise": GameConfig(True, True, True, None, False, False, "FC"),
    "Treasure Raiders": GameConfig(True, True, True, None, False, False, "FC"),
    "Treasures of Odin": GameConfig(True, True, True, None, False, False, "FC"),
    "Tower": GameConfig(True, True, True, None, False, False, "FC"),
    "War of the Universe": GameConfig(True, True, True, None, False, False, "FC"),
    "Win Win Neko": GameConfig(True, True, True, None, False, False, "FC"),
    "Zeus": GameConfig(True, True, True, None, False, False, "FC"),
    # JDB
    "Aviator Extra Bet": GameConfig(False, True, True, True, True, True, "JDB"),
    "Banana Saga": GameConfig(False, True, True, True, True, True, "JDB"),
    "Beer Tycoon": GameConfig(False, True, True, True, True, True, "JDB"),
    "Big Three Dragons": GameConfig(False, True, True, True, True, True, "JDB"),
    "Birds and Animals": GameConfig(False, True, True, True, True, True, "JDB"),
    "Birds Party Deluxe": GameConfig(False, True, True, True, True, True, "JDB"),
    "Boom Fiesta": GameConfig(False, True, True, True, True, True, "JDB"),
    "Bull Treasure": GameConfig(False, True, True, True, True, True, "JDB"),
    "Cai Shen Bingo": GameConfig(False, True, True, True, True, True, "JDB"),
    "Cai Shen Party": GameConfig(False, True, True, True, True, True, "JDB"),
    "Caishen Coming": GameConfig(False, True, True, True, True, True, "JDB"),
    "Chef Panda": GameConfig(False, True, True, True, True, True, "JDB"),
    "Classic Mario": GameConfig(False, True, True, True, True, True, "JDB"),
    "Coo Coo Farm": GameConfig(False, True, True, True, True, True, "JDB"),
    "Crazy King Kong": GameConfig(False, True, True, True, True, True, "JDB"),
    "Dice": GameConfig(False, True, True, True, True, True, "JDB"),
    "Double Wilds": GameConfig(False, True, True, True, True, True, "JDB"),
    "Dragon Soar - Hyper Wild": GameConfig(False, True, True, True, True, True, "JDB"),
    "Dragon Warrior": GameConfig(False, True, True, True, True, True, "JDB"),
    "Dragon's Gate": GameConfig(False, True, True, True, True, True, "JDB"),
    "Egypt Treasure": GameConfig(False, True, True, True, True, True, "JDB"),
    "Firework Burst": GameConfig(False, True, True, True, True, True, "JDB"),
    "Fishin' Fever X-Huge": GameConfig(False, True, True, True, True, True, "JDB"),
    "Flirting Scholar Tang II": GameConfig(False, True, True, True, True, True, "JDB"),
    "Fortune Horse": GameConfig(False, True, True, True, True, True, "JDB"),
    "Fortune Jewel": GameConfig(False, True, True, True, True, True, "JDB"),
    "Fortune Neko": GameConfig(False, True, True, True, True, True, "JDB"),
    "Fortune Treasure": GameConfig(False, True, True, True, True, True, "JDB"),
    "Fruity Bonanza Combo": GameConfig(False, True, True, True, True, True, "JDB"),
    "Funky King Kong": GameConfig(False, True, True, True, True, True, "JDB"),
    "Galaxy Burst": GameConfig(False, True, True, True, True, True, "JDB"),
    "Glamorous Girl": GameConfig(False, True, True, True, True, True, "JDB"),
    "Go Lai Fu": GameConfig(False, True, True, True, True, True, "JDB"),
    "Goal": GameConfig(False, True, True, True, True, True, "JDB"),
    "Golden Disco": GameConfig(False, True, True, True, True, True, "JDB"),
    "Guan Gong": GameConfig(False, True, True, True, True, True, "JDB"),
    "Happy New Year": GameConfig(False, True, True, True, True, True, "JDB"),
    "HiLo": GameConfig(False, True, True, True, True, True, "JDB"),
    "Horse Racing": GameConfig(False, True, True, True, True, True, "JDB"),
    "Huaguoshan Legends": GameConfig(False, True, True, True, True, True, "JDB"),
    "Jogo Do Bicho": GameConfig(False, True, True, True, True, True, "JDB"),
    "Jungle Jungle": GameConfig(False, True, True, True, True, True, "JDB"),
    "King of Football": GameConfig(False, True, True, True, True, True, "JDB"),
    "Koi Trio": GameConfig(False, True, True, True, True, True, "JDB"),
    "Lantern Wealth": GameConfig(False, True, True, True, True, True, "JDB"),
    "Legendary 5": GameConfig(False, True, True, True, True, True, "JDB"),
    "Llama Adventure": GameConfig(False, True, True, True, True, True, "JDB"),
    "Lucky Color Game": GameConfig(False, True, True, True, True, True, "JDB"),
    "Lucky Diamond": GameConfig(False, True, True, True, True, True, "JDB"),
    "Lucky Dragon": GameConfig(False, True, True, True, True, True, "JDB"),
    "Lucky Dragons": GameConfig(False, True, True, True, True, True, "JDB"),
    "Lucky Qilin": GameConfig(False, True, True, True, True, True, "JDB"),
    "Lucky Racing": GameConfig(False, True, True, True, True, True, "JDB"),
    "Magic Ace Wild Lock": GameConfig(False, True, True, True, True, True, "JDB"),
    "Mahjong": GameConfig(False, True, True, True, True, True, "JDB"),
    "Maya Gold Crazy": GameConfig(False, True, True, True, True, True, "JDB"),
    "Miner Babe": GameConfig(False, True, True, True, True, True, "JDB"),
    "Mines": GameConfig(False, True, True, True, True, True, "JDB"),
    "Mines 2": GameConfig(False, True, True, True, True, True, "JDB"),
    "Mining Upstart": GameConfig(False, True, True, True, True, True, "JDB"),
    "Mjolnir": GameConfig(False, True, True, True, True, True, "JDB"),
    "Mole Crash": GameConfig(False, True, True, True, True, True, "JDB"),
    "Moneybags Man": GameConfig(False, True, True, True, True, True, "JDB"),
    "Napoleon": GameConfig(False, True, True, True, True, True, "JDB"),
    "Olympig": GameConfig(False, True, True, True, True, True, "JDB"),
    "One Punch Man": GameConfig(False, True, True, True, True, True, "JDB"),
    "Orient Animals": GameConfig(False, True, True, True, True, True, "JDB"),
    "Panda Panda": GameConfig(False, True, True, True, True, True, "JDB"),
    "Pirate Treasure": GameConfig(False, True, True, True, True, True, "JDB"),
    "Plinko": GameConfig(False, True, True, True, True, True, "JDB"),
    "Pop Pop Candy 1000": GameConfig(False, True, True, True, True, True, "JDB"),
    "Prosperity Tiger": GameConfig(False, True, True, True, True, True, "JDB"),
    "Ragnarok: Thor vs Loki": GameConfig(False, True, True, True, True, True, "JDB"),
    "Rocket Derby": GameConfig(False, True, True, True, True, True, "JDB"),
    "Rolling in Money": GameConfig(False, True, True, True, True, True, "JDB"),
    "Rooster in Love": GameConfig(False, True, True, True, True, True, "JDB"),
    "Spindrift": GameConfig(False, True, True, True, True, True, "JDB"),
    "Spindrift 2": GameConfig(False, True, True, True, True, True, "JDB"),
    "Super Niubi Deluxe": GameConfig(False, True, True, True, True, True, "JDB"),
    "Super Super Fruit": GameConfig(False, True, True, True, True, True, "JDB"),
    "The Llama Adventure": GameConfig(False, True, True, True, True, True, "JDB"),
    "Triple King Kong": GameConfig(False, True, True, True, True, True, "JDB"),
    "Wealthway": GameConfig(False, True, True, True, True, True, "JDB"),
    "Winning Mask": GameConfig(False, True, True, True, True, True, "JDB"),
    "Wonder Elephant": GameConfig(False, True, True, True, True, True, "JDB"),
    "Xi Yang Yang": GameConfig(False, True, True, True, True, True, "JDB"),
    # Pragmatic Play
    "3 Buzzing Wilds": GameConfig(False, True, True, True, True, True, "PP"),
    "3 Dancing Monkeys": GameConfig(False, True, True, True, True, True, "PP"),
    "3 Dancing Monkeys™": GameConfig(False, True, True, True, True, True, "PP"),
    "5 Frozen Charms Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "5 Lions Dance": GameConfig(False, True, True, True, True, True, "PP"),
    "5 Rabbits Megaways™": GameConfig(False, True, True, True, True, True, "PP"),
    "6 Jokers": GameConfig(False, True, True, True, True, True, "PP"),
    "7 Clovers of Fortune": GameConfig(False, True, True, True, True, True, "PP"),
    "7 Piggies": GameConfig(False, True, True, True, True, True, "PP"),
    "8 Golden Dragon Challenge": GameConfig(False, True, True, True, True, True, "PP"),
    "888 Bonanza™": GameConfig(False, True, True, True, True, True, "PP"),
    "888 Gold": GameConfig(False, True, True, True, True, True, "PP"),
    "African Elephant": GameConfig(False, True, True, True, True, True, "PP"),
    "Aladdin and the Sorcerer": GameConfig(False, True, True, True, True, True, "PP"),
    "Angel vs Sinner": GameConfig(False, True, True, True, True, True, "PP"),
    "Anime Mecha Megaways™": GameConfig(False, True, True, True, True, True, "PP"),
    "Aztec Blaze™": GameConfig(False, True, True, True, True, True, "PP"),
    "Aztec Bonanza": GameConfig(False, True, True, True, True, True, "PP"),
    "Aztec Gems": GameConfig(False, True, True, True, True, True, "PP"),
    "Aztec Gems Deluxe": GameConfig(False, True, True, True, True, True, "PP"),
    "Aztec Powernudge": GameConfig(False, True, True, True, True, True, "PP"),
    "Aztec Treasure Hunt": GameConfig(False, True, True, True, True, True, "PP"),
    "Badge Blitz": GameConfig(False, True, True, True, True, True, "PP"),
    "Bali Dragon": GameConfig(False, True, True, True, True, True, "PP"),
    "Barn Festival": GameConfig(False, True, True, True, True, True, "PP"),
    "Barnyard Megahays Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Beware The Deep Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Amazon Xtreme": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Bonanza": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Bonanza - Keeping It Reel": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Bonanza - Reel Action": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Bonanza Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Christmas Bash": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Christmas Bash™ (Reel Kingdom Game)": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Crash": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Day at the Races": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Floats My Boat": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Halloween": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Hold & Spinner": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Hold & Spinner Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Mission Fishin'": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Secrets of the Golden Lake": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Splash": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Vegas Double Down Deluxe": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Bass Xmas Xtreme": GameConfig(False, True, True, True, True, True, "PP"),
    "Big Juan": GameConfig(False, True, True, True, True, True, "PP"),
    "Bigger Bass Blizzard - Christmas Catch": GameConfig(False, True, True, True, True, True, "PP"),
    "Bigger Bass Bonanza": GameConfig(False, True, True, True, True, True, "PP"),
    "Black Bull": GameConfig(False, True, True, True, True, True, "PP"),
    "Blade & Fangs": GameConfig(False, True, True, True, True, True, "PP"),
    "Blazing Wilds Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Bomb Bonanza": GameConfig(False, True, True, True, True, True, "PP"),
    "Book of Golden Sands": GameConfig(False, True, True, True, True, True, "PP"),
    "Book of Tut Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Bounty Gold": GameConfig(False, True, True, True, True, True, "PP"),
    "Bow of Artemis": GameConfig(False, True, True, True, True, True, "PP"),
    "Buffalo King": GameConfig(False, True, True, True, True, True, "PP"),
    "Buffalo King Untamed Megaways™": GameConfig(False, True, True, True, True, True, "PP"),
    "Caishen's Gold": GameConfig(False, True, True, True, True, True, "PP"),
    "Candy Blitz Bombs": GameConfig(False, True, True, True, True, True, "PP"),
    "Candy Corner": GameConfig(False, True, True, True, True, True, "PP"),
    "Candy Jar Cluster": GameConfig(False, True, True, True, True, True, "PP"),
    "Candy Jar Clusters": GameConfig(False, True, True, True, True, True, "PP"),
    "Candy Stars": GameConfig(False, True, True, True, True, True, "PP"),
    "Cash Bonanza": GameConfig(False, True, True, True, True, True, "PP"),
    "Cash Box": GameConfig(False, True, True, True, True, True, "PP"),
    "Cash Box™": GameConfig(False, True, True, True, True, True, "PP"),
    "Cash Chips": GameConfig(False, True, True, True, True, True, "PP"),
    "Cash Elevator": GameConfig(False, True, True, True, True, True, "PP"),
    "Casino Heist Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Castle of Fire": GameConfig(False, True, True, True, True, True, "PP"),
    "Chase for Glory": GameConfig(False, True, True, True, True, True, "PP"),
    "Cheeky Emperor™": GameConfig(False, True, True, True, True, True, "PP"),
    "Chests of Cai Shen": GameConfig(False, True, True, True, True, True, "PP"),
    "Chicken Chase – Caccia alla Gallina": GameConfig(False, True, True, True, True, True, "PP"),
    "Chicken Drop": GameConfig(False, True, True, True, True, True, "PP"),
    "Chilli Heat Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Christmas Big Bass Bonanza": GameConfig(False, True, True, True, True, True, "PP"),
    "Christmas Carol Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Cleocatra": GameConfig(False, True, True, True, True, True, "PP"),
    "Clover Gold": GameConfig(False, True, True, True, True, True, "PP"),
    "Club Tropicana": GameConfig(False, True, True, True, True, True, "PP"),
    "Coffee Wild™": GameConfig(False, True, True, True, True, True, "PP"),
    "Colossal Cash Zone": GameConfig(False, True, True, True, True, True, "PP"),
    "Congo Cash": GameConfig(False, True, True, True, True, True, "PP"),
    "Congo Cash XL": GameConfig(False, True, True, True, True, True, "PP"),
    "Cosmic Cash": GameConfig(False, True, True, True, True, True, "PP"),
    "Cowboy Coins": GameConfig(False, True, True, True, True, True, "PP"),
    "Cowboys Gold": GameConfig(False, True, True, True, True, True, "PP"),
    "Crank it Up": GameConfig(False, True, True, True, True, True, "PP"),
    "Crown of Fire": GameConfig(False, True, True, True, True, True, "PP"),
    "Crystal Caverns Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Curse of the Werewolf Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Cyber Heist": GameConfig(False, True, True, True, True, True, "PP"),
    "Cyclops Smash": GameConfig(False, True, True, True, True, True, "PP"),
    "Dance Party": GameConfig(False, True, True, True, True, True, "PP"),
    "Day of Dead": GameConfig(False, True, True, True, True, True, "PP"),
    "Demon Pots": GameConfig(False, True, True, True, True, True, "PP"),
    "Demon Pots™": GameConfig(False, True, True, True, True, True, "PP"),
    "Devilicious": GameConfig(False, True, True, True, True, True, "PP"),
    "Diamond Cascade": GameConfig(False, True, True, True, True, True, "PP"),
    "Diamond Strike": GameConfig(False, True, True, True, True, True, "PP"),
    "Diamonds of Egypt": GameConfig(False, True, True, True, True, True, "PP"),
    "Ding Dong Christmas Bells": GameConfig(False, True, True, True, True, True, "PP"),
    "Down the Rails": GameConfig(False, True, True, True, True, True, "PP"),
    "Dragon Gold 88": GameConfig(False, True, True, True, True, True, "PP"),
    "Dragon Hero": GameConfig(False, True, True, True, True, True, "PP"),
    "Dragon Hero™": GameConfig(False, True, True, True, True, True, "PP"),
    "Dragon Hot Hold and Spin": GameConfig(False, True, True, True, True, True, "PP"),
    "Dragon Kingdom - Eyes of Fire": GameConfig(False, True, True, True, True, True, "PP"),
    "Dwarf & Dragon": GameConfig(False, True, True, True, True, True, "PP"),
    "Dynamite Diggin Doug": GameConfig(False, True, True, True, True, True, "PP"),
    "Egyptian Fortunes": GameConfig(False, True, True, True, True, True, "PP"),
    "Elemental Gems Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Emerald King Rainbow Road": GameConfig(False, True, True, True, True, True, "PP"),
    "Empty the Bank": GameConfig(False, True, True, True, True, True, "PP"),
    "Excalibur Unleashed": GameConfig(False, True, True, True, True, True, "PP"),
    "Extra Juicy Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Eye of Cleopatra": GameConfig(False, True, True, True, True, True, "PP"),
    "Eye of the Storm": GameConfig(False, True, True, True, True, True, "PP"),
    "Fairytale Fortune": GameConfig(False, True, True, True, True, True, "PP"),
    "Fat Panda": GameConfig(False, True, True, True, True, True, "PP"),
    "Fiery Wild Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Fire Archer": GameConfig(False, True, True, True, True, True, "PP"),
    "Fire Hot 100": GameConfig(False, True, True, True, True, True, "PP"),
    "Fire Hot 20": GameConfig(False, True, True, True, True, True, "PP"),
    "Fire Hot 40": GameConfig(False, True, True, True, True, True, "PP"),
    "Fire Hot 5": GameConfig(False, True, True, True, True, True, "PP"),
    "Fire Portals": GameConfig(False, True, True, True, True, True, "PP"),
    "Fire Strike": GameConfig(False, True, True, True, True, True, "PP"),
    "Fire Strike 2": GameConfig(False, True, True, True, True, True, "PP"),
    "Firebird Spirit": GameConfig(False, True, True, True, True, True, "PP"),
    "Fish Eye": GameConfig(False, True, True, True, True, True, "PP"),
    "Fishin' Reels": GameConfig(False, True, True, True, True, True, "PP"),
    "Floating Dragon": GameConfig(False, True, True, True, True, True, "PP"),
    "Floating Dragon - Dragon Boat Festival": GameConfig(False, True, True, True, True, True, "PP"),
    "Floating Dragon Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Floating Dragon New Year Festival Ultra Megaways Hold & Spin": GameConfig(False, True, True, True, True, True, "PP"),
    "Fortune Ace": GameConfig(False, True, True, True, True, True, "PP"),
    "Fortune Dragon": GameConfig(False, True, True, True, True, True, "PP"),
    "Fortune Hit'n Roll": GameConfig(False, True, True, True, True, True, "PP"),
    "Fortunes of Aztec": GameConfig(False, True, True, True, True, True, "PP"),
    "Frogs & Bugs": GameConfig(False, True, True, True, True, True, "PP"),
    "Frozen Tropics": GameConfig(False, True, True, True, True, True, "PP"),
    "Fruit Party": GameConfig(False, True, True, True, True, True, "PP"),
    "Fruit Party 2": GameConfig(False, True, True, True, True, True, "PP"),
    "Fruit Rainbow": GameConfig(False, True, True, True, True, True, "PP"),
    "Fruits of the Amazon": GameConfig(False, True, True, True, True, True, "PP"),
    "Fruity Treats": GameConfig(False, True, True, True, True, True, "PP"),
    "Fury of Odin Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Gates of Gatot Kaca": GameConfig(False, True, True, True, True, True, "PP"),
    "Gates of Olympus": GameConfig(False, True, True, True, True, True, "PP"),
    "Gates of Olympus 1000": GameConfig(False, True, True, True, True, True, "PP"),
    "Gems Bonanza": GameConfig(False, True, True, True, True, True, "PP"),
    "Genie 3 Wishes": GameConfig(False, True, True, True, True, True, "PP"),
    "Genie Mega Reels": GameConfig(False, True, True, True, True, True, "PP"),
    "Ghostbusters": GameConfig(False, True, True, True, True, True, "PP"),
    "Gladiator Legends": GameConfig(False, True, True, True, True, True, "PP"),
    "Goblin Heist Powernudge": GameConfig(False, True, True, True, True, True, "PP"),
    "Gold Party": GameConfig(False, True, True, True, True, True, "PP"),
    "Gold Rush": GameConfig(False, True, True, True, True, True, "PP"),
    "Gold Train": GameConfig(False, True, True, True, True, True, "PP"),
    "Golden Dragon Inferno": GameConfig(False, True, True, True, True, True, "PP"),
    "Golden Pig": GameConfig(False, True, True, True, True, True, "PP"),
    "Golden Piggy Bank": GameConfig(False, True, True, True, True, True, "PP"),
    "Golden Tiger": GameConfig(False, True, True, True, True, True, "PP"),
    "Greek Gods": GameConfig(False, True, True, True, True, True, "PP"),
    "Greedy Wolf": GameConfig(False, True, True, True, True, True, "PP"),
    "Green Chilli": GameConfig(False, True, True, True, True, True, "PP"),
    "Grizzly Gold": GameConfig(False, True, True, True, True, True, "PP"),
    "Guardians of The Monastery": GameConfig(False, True, True, True, True, True, "PP"),
    "Guardians of the Void": GameConfig(False, True, True, True, True, True, "PP"),
    "Hercules & Pegasus": GameConfig(False, True, True, True, True, True, "PP"),
    "Heroes Hunt": GameConfig(False, True, True, True, True, True, "PP"),
    "Hot Fiesta": GameConfig(False, True, True, True, True, True, "PP"),
    "Hot Pepper": GameConfig(False, True, True, True, True, True, "PP"),
    "Hot Safari": GameConfig(False, True, True, True, True, True, "PP"),
    "Hot to Burn": GameConfig(False, True, True, True, True, True, "PP"),
    "Hot to Burn Extreme": GameConfig(False, True, True, True, True, True, "PP"),
    "Hot to Burn Hold & Spin": GameConfig(False, True, True, True, True, True, "PP"),
    "Hot to Burn Jackpot": GameConfig(False, True, True, True, True, True, "PP"),
    "Hot Triple Sevens": GameConfig(False, True, True, True, True, True, "PP"),
    "Irish Charms": GameConfig(False, True, True, True, True, True, "PP"),
    "Irish Clover": GameConfig(False, True, True, True, True, True, "PP"),
    "Irish Clover 100": GameConfig(False, True, True, True, True, True, "PP"),
    "Irish Pot Luck": GameConfig(False, True, True, True, True, True, "PP"),
    "Jasmine Dreams": GameConfig(False, True, True, True, True, True, "PP"),
    "Joker King": GameConfig(False, True, True, True, True, True, "PP"),
    "Jokers Jewels": GameConfig(False, True, True, True, True, True, "PP"),
    "John Hunter and the Aztec Treasure": GameConfig(False, True, True, True, True, True, "PP"),
    "John Hunter and the Book of Tut": GameConfig(False, True, True, True, True, True, "PP"),
    "John Hunter and the Book of Tut Respin": GameConfig(False, True, True, True, True, True, "PP"),
    "John Hunter and the Mayan Gods": GameConfig(False, True, True, True, True, True, "PP"),
    "John Hunter and the Quest for Bermuda Riches": GameConfig(False, True, True, True, True, True, "PP"),
    "John Hunter and the Tomb of the Scarab Queen": GameConfig(False, True, True, True, True, True, "PP"),
    "Joker’s Coins Hold & Win": GameConfig(False, True, True, True, True, True, "PP"),
    "Kingdom of The Dead": GameConfig(False, True, True, True, True, True, "PP"),
    "Knight Hot Spotz": GameConfig(False, True, True, True, True, True, "PP"),
    "Kraken's Sky Bounty": GameConfig(False, True, True, True, True, True, "PP"),
    "Legend of Heroes Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Legend of The Golden Monkey": GameConfig(False, True, True, True, True, True, "PP"),
    "Little Gem": GameConfig(False, True, True, True, True, True, "PP"),
    "Little Gem Hold & Spin": GameConfig(False, True, True, True, True, True, "PP"),
    "Loch Ness Loot": GameConfig(False, True, True, True, True, True, "PP"),
    "Lucky Dragons": GameConfig(False, True, True, True, True, True, "PP"),
    "Lucky Grace and Charm": GameConfig(False, True, True, True, True, True, "PP"),
    "Lucky Lightning": GameConfig(False, True, True, True, True, True, "PP"),
    "Lucky, Grace & Charm Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Magic Journey": GameConfig(False, True, True, True, True, True, "PP"),
    "Mahjong Wins": GameConfig(False, True, True, True, True, True, "PP"),
    "Mahjong Wins 2": GameConfig(False, True, True, True, True, True, "PP"),
    "Master Chen's Fortune": GameConfig(False, True, True, True, True, True, "PP"),
    "Medusa Strike": GameConfig(False, True, True, True, True, True, "PP"),
    "Mega Don": GameConfig(False, True, True, True, True, True, "PP"),
    "Mega Wheel": GameConfig(False, True, True, True, True, True, "PP"),
    "MegaWheel™": GameConfig(False, True, True, True, True, True, "PP"),
    "Mighty Kong": GameConfig(False, True, True, True, True, True, "PP"),
    "Mochimon": GameConfig(False, True, True, True, True, True, "PP"),
    "Monster Superlanche": GameConfig(False, True, True, True, True, True, "PP"),
    "Monkey Warrior": GameConfig(False, True, True, True, True, True, "PP"),
    "Mummyland Treasures": GameConfig(False, True, True, True, True, True, "PP"),
    "Mystery of the Orient": GameConfig(False, True, True, True, True, True, "PP"),
    "Mystic Chief": GameConfig(False, True, True, True, True, True, "PP"),
    "Nile Fortune": GameConfig(False, True, True, True, True, True, "PP"),
    "North Guardians": GameConfig(False, True, True, True, True, True, "PP"),
    "Octobeer Fortunes": GameConfig(False, True, True, True, True, True, "PP"),
    "Old Gold Miner Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Oodles of Noodles": GameConfig(False, True, True, True, True, True, "PP"),
    "Panda Fortune 2": GameConfig(False, True, True, True, True, True, "PP"),
    "Peak Power": GameConfig(False, True, True, True, True, True, "PP"),
    "Penguins Christmas Party Time": GameConfig(False, True, True, True, True, True, "PP"),
    "Phoenix Forge": GameConfig(False, True, True, True, True, True, "PP"),
    "Piggy Bank Bills": GameConfig(False, True, True, True, True, True, "PP"),
    "Piggy Bankers": GameConfig(False, True, True, True, True, True, "PP"),
    "Pinup Girls": GameConfig(False, True, True, True, True, True, "PP"),
    "Pirate Gold Deluxe": GameConfig(False, True, True, True, True, True, "PP"),
    "Pirate Golden Age": GameConfig(False, True, True, True, True, True, "PP"),
    "Pirates Pub": GameConfig(False, True, True, True, True, True, "PP"),
    "Pixie Wings": GameConfig(False, True, True, True, True, True, "PP"),
    "Pompeii Megareels Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Pot of Fortune": GameConfig(False, True, True, True, True, True, "PP"),
    "Power of Merlin Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Power of Ninja": GameConfig(False, True, True, True, True, True, "PP"),
    "Pub Kings": GameConfig(False, True, True, True, True, True, "PP"),
    "Pyramid Bonanza": GameConfig(False, True, True, True, True, True, "PP"),
    "Pyramid King": GameConfig(False, True, True, True, True, True, "PP"),
    "Queen of Gods": GameConfig(False, True, True, True, True, True, "PP"),
    "Queenie": GameConfig(False, True, True, True, True, True, "PP"),
    "Rabbit Garden": GameConfig(False, True, True, True, True, True, "PP"),
    "Rainbow Gold": GameConfig(False, True, True, True, True, True, "PP"),
    "Rainbow Reels": GameConfig(False, True, True, True, True, True, "PP"),
    "Reel Banks": GameConfig(False, True, True, True, True, True, "PP"),
    "Release the Bison": GameConfig(False, True, True, True, True, True, "PP"),
    "Release the Kraken": GameConfig(False, True, True, True, True, True, "PP"),
    "Release the Kraken 2": GameConfig(False, True, True, True, True, True, "PP"),
    "Release the Kraken Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Revenge of Loki Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Ripe Rewards": GameConfig(False, True, True, True, True, True, "PP"),
    "Rise of Giza Powernudge": GameConfig(False, True, True, True, True, True, "PP"),
    "Rise of Samurai 4": GameConfig(False, True, True, True, True, True, "PP"),
    "Robber Strike": GameConfig(False, True, True, True, True, True, "PP"),
    "Rocket Blast Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Rujak Bonanza": GameConfig(False, True, True, True, True, True, "PP"),
    "Running Sushi": GameConfig(False, True, True, True, True, True, "PP"),
    "Saiyan Mania": GameConfig(False, True, True, True, True, True, "PP"),
    "Samurai Code": GameConfig(False, True, True, True, True, True, "PP"),
    "Santa": GameConfig(False, True, True, True, True, True, "PP"),
    "Santa's Great Gifts": GameConfig(False, True, True, True, True, True, "PP"),
    "Santa's Wonderland": GameConfig(False, True, True, True, True, True, "PP"),
    "Santa’s Xmas Rush": GameConfig(False, True, True, True, True, True, "PP"),
    "Sea Fantasy": GameConfig(False, True, True, True, True, True, "PP"),
    "Secret City Gold": GameConfig(False, True, True, True, True, True, "PP"),
    "Shield of Sparta": GameConfig(False, True, True, True, True, True, "PP"),
    "Shining Hot 100": GameConfig(False, True, True, True, True, True, "PP"),
    "Shining Hot 20": GameConfig(False, True, True, True, True, True, "PP"),
    "Shining Hot 40": GameConfig(False, True, True, True, True, True, "PP"),
    "Shining Hot 5": GameConfig(False, True, True, True, True, True, "PP"),
    "Sky Bounty": GameConfig(False, True, True, True, True, True, "PP"),
    "Smugglers Cove": GameConfig(False, True, True, True, True, True, "PP"),
    "Snakes & Ladders - Snake Eyes": GameConfig(False, True, True, True, True, True, "PP"),
    "Snakes and Ladders Megadice": GameConfig(False, True, True, True, True, True, "PP"),
    "Spaceman": GameConfig(False, True, True, True, True, True, "PP"),
    "Spartan King": GameConfig(False, True, True, True, True, True, "PP"),
    "Spellbinding Mystery": GameConfig(False, True, True, True, True, True, "PP"),
    "Spin & Score Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Spirit of Adventure": GameConfig(False, True, True, True, True, True, "PP"),
    "Star Bounty": GameConfig(False, True, True, True, True, True, "PP"),
    "Star Pirates Code": GameConfig(False, True, True, True, True, True, "PP"),
    "Starlight Christmas": GameConfig(False, True, True, True, True, True, "PP"),
    "Starlight Princess 1000": GameConfig(False, True, True, True, True, True, "PP"),
    "Starlight Princess Pachi": GameConfig(False, True, True, True, True, True, "PP"),
    "Starz Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Strawberry Cocktail": GameConfig(False, True, True, True, True, True, "PP"),
    "Street Racer": GameConfig(False, True, True, True, True, True, "PP"),
    "Striking Hot 5": GameConfig(False, True, True, True, True, True, "PP"),
    "Sugar Rush": GameConfig(False, True, True, True, True, True, "PP"),
    "Sugar Rush 1000": GameConfig(False, True, True, True, True, True, "PP"),
    "Sugar Rush™": GameConfig(False, True, True, True, True, True, "PP"),
    "Sumo Supreme Megaways": GameConfig(False, True, True, True, True, True, "PP"),
    "Super Joker": GameConfig(False, True, True, True, True, True, "PP"),
    "Super X": GameConfig(False, True, True, True, True, True, "PP"),
    "Supermania": GameConfig(False, True, True, True, True, True, "PP"),
    "Sweet Bonanza 1000": GameConfig(False, True, True, True, True, True, "PP"),
    "Sweet Bonanza Xmas": GameConfig(False, True, True, True, True, True, "PP"),
    "Sweet Powernudge": GameConfig(False, True, True, True, True, True, "PP"),
    # BNG
    "15 Dragon Pearls": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 African Drums": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Aztec Temples": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Carts of Gold": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Chillies and Joker: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 China Pots": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Clover Pots": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Clover Pots Extra": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Coin Volcanoes": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Coins": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Coins: Egypt": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Egypt Chests": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Fortune Trees": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Hot Chillies": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Hungry Pandas": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Luxor Pots: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Magic Lamps: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Pirate Barrels: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Pots Riches: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Pots Riches Extra: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Pots of Egypt": GameConfig(False, True, True, True, True, True, "BNG"),
    "3 Super Hot Chillies: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "777 Coins": GameConfig(False, True, True, True, True, True, "BNG"),
    "777 Fruity Classic": GameConfig(False, True, True, True, True, True, "BNG"),
    "777 Gems Respin": GameConfig(False, True, True, True, True, True, "BNG"),
    "African Spirit Sticky Wilds": GameConfig(False, True, True, True, True, True, "BNG"),
    "Amazonia Spirit": GameConfig(False, True, True, True, True, True, "BNG"),
    "Arizona Heist: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Aztec Fire - Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Aztec Fire 2 - Hold and Win Multi": GameConfig(False, True, True, True, True, True, "BNG"),
    "Aztec Sun": GameConfig(False, True, True, True, True, True, "BNG"),
    "Big Heist": GameConfig(False, True, True, True, True, True, "BNG"),
    "Black Wolf": GameConfig(False, True, True, True, True, True, "BNG"),
    "Black Wolf 2": GameConfig(False, True, True, True, True, True, "BNG"),
    "Bluffy Cat": GameConfig(False, True, True, True, True, True, "BNG"),
    "Book of Sun": GameConfig(False, True, True, True, True, True, "BNG"),
    "Book of Sun: Choice": GameConfig(False, True, True, True, True, True, "BNG"),
    "Book of Sun: Multichance": GameConfig(False, True, True, True, True, True, "BNG"),
    "Book of Wizard": GameConfig(False, True, True, True, True, True, "BNG"),
    "Book of Wizard: Crystal Chance": GameConfig(False, True, True, True, True, True, "BNG"),
    "Boom! Boom! Gold!": GameConfig(False, True, True, True, True, True, "BNG"),
    "Buddha Fortune": GameConfig(False, True, True, True, True, True, "BNG"),
    "Buffalo Power": GameConfig(False, True, True, True, True, True, "BNG"),
    "Buffalo Power 2: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Buffalo Power Megaways": GameConfig(False, True, True, True, True, True, "BNG"),
    "Caishen Wealth": GameConfig(False, True, True, True, True, True, "BNG"),
    "Candy Boom": GameConfig(False, True, True, True, True, True, "BNG"),
    "Cash Volcano": GameConfig(False, True, True, True, True, True, "BNG"),
    "China Festival": GameConfig(False, True, True, True, True, True, "BNG"),
    "Clover Charm: Hit the Bonus": GameConfig(False, True, True, True, True, True, "BNG"),
    "Coin Lamp": GameConfig(False, True, True, True, True, True, "BNG"),
    "Coin Strike: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Coin Up: Hot Fire": GameConfig(False, True, True, True, True, True, "BNG"),
    "Coin Up: Lightning": GameConfig(False, True, True, True, True, True, "BNG"),
    "Coin Volcano - Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Crown and Diamonds: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Crystal Scarabs": GameConfig(False, True, True, True, True, True, "BNG"),
    "Dancing Joker": GameConfig(False, True, True, True, True, True, "BNG"),
    "Diamonds Power: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Dragon Pearls": GameConfig(False, True, True, True, True, True, "BNG"),
    "Dragon Wealth": GameConfig(False, True, True, True, True, True, "BNG"),
    "Dragon Wealth - Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Eggs of Gold": GameConfig(False, True, True, True, True, True, "BNG"),
    "Egypt Fire": GameConfig(False, True, True, True, True, True, "BNG"),
    "Energy Coins: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Energy Joker: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Eye of Gold": GameConfig(False, True, True, True, True, True, "BNG"),
    "Fire Coins: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Fire Temple: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Fishin' Bear": GameConfig(False, True, True, True, True, True, "BNG"),
    "Flash Joker: Fever": GameConfig(False, True, True, True, True, True, "BNG"),
    "Forest Spirit": GameConfig(False, True, True, True, True, True, "BNG"),
    "Fortune Globe": GameConfig(False, True, True, True, True, True, "BNG"),
    "Fruits & Joker Fever": GameConfig(False, True, True, True, True, True, "BNG"),
    "Fruits & Sevens: Fever": GameConfig(False, True, True, True, True, True, "BNG"),
    "Fruits Fever 5 Lines": GameConfig(False, True, True, True, True, True, "BNG"),
    "Goddess of Egypt": GameConfig(False, True, True, True, True, True, "BNG"),
    "Gold Express": GameConfig(False, True, True, True, True, True, "BNG"),
    "Gold Nuggets": GameConfig(False, True, True, True, True, True, "BNG"),
    "Golden Dancing Lion": GameConfig(False, True, True, True, True, True, "BNG"),
    "Golden Teapot": GameConfig(False, True, True, True, True, True, "BNG"),
    "Grab More Gold!": GameConfig(False, True, True, True, True, True, "BNG"),
    "Great Panda": GameConfig(False, True, True, True, True, True, "BNG"),
    "Green Chilli": GameConfig(False, True, True, True, True, True, "BNG"),
    "Green Chilli 2": GameConfig(False, True, True, True, True, True, "BNG"),
    "Happy Fish": GameConfig(False, True, True, True, True, True, "BNG"),
    "Hawaii Riches: Bonus Vault": GameConfig(False, True, True, True, True, True, "BNG"),
    "Hit More Gold": GameConfig(False, True, True, True, True, True, "BNG"),
    "Hit the Gold!": GameConfig(False, True, True, True, True, True, "BNG"),
    "Hot Chilli Joker": GameConfig(False, True, True, True, True, True, "BNG"),
    "Hot Fire Fruits": GameConfig(False, True, True, True, True, True, "BNG"),
    "Jingle Coins: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "King of the Sky: Hit the Bonus": GameConfig(False, True, True, True, True, True, "BNG"),
    "Lady Fortune": GameConfig(False, True, True, True, True, True, "BNG"),
    "Lamp of Wonder": GameConfig(False, True, True, True, True, True, "BNG"),
    "Lava Coins": GameConfig(False, True, True, True, True, True, "BNG"),
    "Legend of Cleopatra Megaways": GameConfig(False, True, True, True, True, True, "BNG"),
    "Lightning Clovers: Hit the Bonus": GameConfig(False, True, True, True, True, True, "BNG"),
    "Lion Coins": GameConfig(False, True, True, True, True, True, "BNG"),
    "Lion Gems: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Little Farm": GameConfig(False, True, True, True, True, True, "BNG"),
    "Lord Fortune 2": GameConfig(False, True, True, True, True, True, "BNG"),
    "Lotus Charm": GameConfig(False, True, True, True, True, True, "BNG"),
    "Lucky Penny": GameConfig(False, True, True, True, True, True, "BNG"),
    "Luxor Gold: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Magic Apple": GameConfig(False, True, True, True, True, True, "BNG"),
    "Magic Apple 2": GameConfig(False, True, True, True, True, True, "BNG"),
    "Magic Ball: Multichance": GameConfig(False, True, True, True, True, True, "BNG"),
    "Mammoth Peak: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Mariachi Lock": GameConfig(False, True, True, True, True, True, "BNG"),
    "Maya Sun": GameConfig(False, True, True, True, True, True, "BNG"),
    "Merry Giftmas: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Moon Sisters": GameConfig(False, True, True, True, True, True, "BNG"),
    "More Magic Apple": GameConfig(False, True, True, True, True, True, "BNG"),
    "Nights of Fire": GameConfig(False, True, True, True, True, True, "BNG"),
    "Olaf Viking": GameConfig(False, True, True, True, True, True, "BNG"),
    "Olympian Gods": GameConfig(False, True, True, True, True, True, "BNG"),
    "Pearl Diver": GameConfig(False, True, True, True, True, True, "BNG"),
    "Pearl Diver 2: Treasure Chest": GameConfig(False, True, True, True, True, True, "BNG"),
    "Pearl Ocean: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Pig Up": GameConfig(False, True, True, True, True, True, "BNG"),
    "Piggy Power: Hit the Bonus": GameConfig(False, True, True, True, True, True, "BNG"),
    "Pink Joker: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Pirate Chest: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Power Crown: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Power Sun": GameConfig(False, True, True, True, True, True, "BNG"),
    "Queen of the Sun": GameConfig(False, True, True, True, True, True, "BNG"),
    "Rio Gems": GameConfig(False, True, True, True, True, True, "BNG"),
    "Rocket Wins": GameConfig(False, True, True, True, True, True, "BNG"),
    "Royal Coins 2: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Royal Express: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Royal Joker: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Scarab Boost": GameConfig(False, True, True, True, True, True, "BNG"),
    "Scarab Riches": GameConfig(False, True, True, True, True, True, "BNG"),
    "Scarab Temple": GameConfig(False, True, True, True, True, True, "BNG"),
    "Sherwood Coins: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Sky Coins": GameConfig(False, True, True, True, True, True, "BNG"),
    "Sky Pearls": GameConfig(False, True, True, True, True, True, "BNG"),
    "Solar Queen": GameConfig(False, True, True, True, True, True, "BNG"),
    "Solar Temple": GameConfig(False, True, True, True, True, True, "BNG"),
    "Sticky Piggy": GameConfig(False, True, True, True, True, True, "BNG"),
    "Storm of Olympus": GameConfig(False, True, True, True, True, True, "BNG"),
    "Sun of Egypt": GameConfig(False, True, True, True, True, True, "BNG"),
    "Sun of Egypt 2": GameConfig(False, True, True, True, True, True, "BNG"),
    "Sun of Egypt 3": GameConfig(False, True, True, True, True, True, "BNG"),
    "Sun of Egypt 4": GameConfig(False, True, True, True, True, True, "BNG"),
    "Sunlight Princess": GameConfig(False, True, True, True, True, True, "BNG"),
    "Sunny Fruits 2: Hold and Win": GameConfig(False, True, True, True, True, True, "BNG"),
    "Super Hot Chilli": GameConfig(False, True, True, True, True, True, "BNG"),
    "Super Marble": GameConfig(False, True, True, True, True, True, "BNG"),
    # JFF
    # "Fortune Gems (JFF)": GameConfig(False, True, True, None, False, True, "JFF"),
    # "Fortune Gems 2 (JFF)": GameConfig(False, True, True, None, False, True, "JFF"),
    # "Fortune Gems 3 (JFF)": GameConfig(False, True, True, None, False, True, "JFF"),
    # R88
    "Maya Gems": GameConfig(False, True, True, None, False, True, "R88"),
    # Royal Slot Gaming
    "Fortune Gems 4": GameConfig(False, True, True, None, False, False, "RSG"),
    "Super Ace 2": GameConfig(False, True, True, None, False, True, "RSG"),
    # Yellow Bat
    "Atlantis": GameConfig(False, True, True, True, True, True, "YB"),
    "Beasty Bingo": GameConfig(False, True, True, True, True, True, "YB"),
    "Bingo Bingo": GameConfig(False, True, True, True, True, True, "YB"),
    "Bingo Bonanza": GameConfig(False, True, True, True, True, True, "YB"),
    "Boom Boom Marmot": GameConfig(False, True, True, True, True, True, "YB"),
    "Crazy Color Gam": GameConfig(False, True, True, True, True, True, "YB"),
    "Crazy Money": GameConfig(False, True, True, True, True, True, "YB"),
    "Diamond Mines": GameConfig(False, True, True, True, True, True, "YB"),
    "Drago Nova": GameConfig(False, True, True, True, True, True, "YB"),
    "DragoNova": GameConfig(False, True, True, True, True, True, "YB"),
    "Dragon Gems": GameConfig(False, True, True, True, True, True, "YB"),
    "Dragon Gems Super Buy": GameConfig(False, True, True, True, True, True, "YB"),
    "Dragon Gems Wheel": GameConfig(False, True, True, True, True, True, "YB"),
    "EZ Bingo": GameConfig(False, True, True, True, True, True, "YB"),
    "Fortune Treasure": GameConfig(False, True, True, True, True, True, "YB"),
    "Gladiator Link TS": GameConfig(False, True, True, True, True, True, "YB"),
    "Golden Aztec": GameConfig(False, True, True, True, True, True, "YB"),
    "Golden Aztec Mega": GameConfig(False, True, True, True, True, True, "YB"),
    "Heat Bingo": GameConfig(False, True, True, True, True, True, "YB"),
    "Joy Bingo": GameConfig(False, True, True, True, True, True, "YB"),
    "Light of Apollo": GameConfig(False, True, True, True, True, True, "YB"),
    "Lightning Bingo": GameConfig(False, True, True, True, True, True, "YB"),
    "Lucky Meow": GameConfig(False, True, True, True, True, True, "YB"),
    "Magic Lamp Link TS": GameConfig(False, True, True, True, True, True, "YB"),
    "Magical Alchemist": GameConfig(False, True, True, True, True, True, "YB"),
    "Mermaid Sling": GameConfig(False, True, True, True, True, True, "YB"),
    "Mermaid Slingo": GameConfig(False, True, True, True, True, True, "YB"),
    "Money Bingo": GameConfig(False, True, True, True, True, True, "YB"),
    "Money Blast": GameConfig(False, True, True, True, True, True, "YB"),
    "Open Sesame": GameConfig(False, True, True, True, True, True, "YB"),
    "Pirate Legends": GameConfig(False, True, True, True, True, True, "YB"),
    "Power Fortune": GameConfig(False, True, True, True, True, True, "YB"),
    "Rolling 7": GameConfig(False, True, True, True, True, True, "YB"),
    "Royal Ace": GameConfig(False, True, True, True, True, True, "YB"),
    "Royal Hunter": GameConfig(False, True, True, True, True, True, "YB"),
    "Sugar Crush": GameConfig(False, True, True, True, True, True, "YB"),
    "Super Egypt": GameConfig(False, True, True, True, True, True, "YB"),
    "Win Cai Shen": GameConfig(False, True, True, True, True, True, "YB"),
    "Zhao Cai Pao": GameConfig(False, True, True, True, True, True, "YB"),
}

DEFAULT_GAME_CONFIG = GameConfig(False, True, True, None, False, False, None)

ProviderProps = namedtuple("ProviderProps", [ "provider", "color", "img_url" ])

PROVIDERS = {
    "JILI": ProviderProps("Jili", LRED, "41786877e5b48c0f35948ec66abdc1bd"),
    "PG": ProviderProps("Pocket Game Soft", LCYN, "02ee299d177a5a4f39645cf0392243b0"),
    "FC": ProviderProps("Fa Chai", YEL, "25bd8e424761c1572da6d990e8515e52"),
    "PP": ProviderProps("Pragmatic Play", LMAG, "aea0a2cbc715c3d2ce3d0e802361d859"),
    "BNG": ProviderProps("BNG", GRE, "61ae92544fbe87d4271f20e29ca389a1"),
    "JDB": ProviderProps("JDB", LBLU, "7594bb75a92e18ff81c7c8e1d65a6dad"),
    "YB": ProviderProps("Yellow Bat", LYEL, "92ee026c472b91d14c61e38d32cce3eb"),
    "CQ9": ProviderProps("CQ9", CYN, "cq9"),
    "CEWIN": ProviderProps("CE Win", MAG, "abf4cf415aa6292c7fca502425c987d5"),
    "MW": ProviderProps("Mega Win", BLU, "3bf4202ead643e783126554143bd52e0"),
    "RSG": ProviderProps("Royal Slot Gaming", RED, "4ac8285dc8ba6fb336c5bafb3c10b246"),
    "R88": ProviderProps("R88", DGRY, "7a45dcd8865cc3922917682df217571a"),
    "KA": ProviderProps("KA Gaming", LGRE, "50ea64224d3e6b76c68bdd6e39740661"),
    "SG": ProviderProps("Spadegaming", LGRY, "027a3554136a9f4b03bbf92e25da6396"),
    "NE": ProviderProps("NET Entertainment", BDGRY, "2f61a64aa0e14422adf6334f52fc1bf0"),
    "AMS": ProviderProps("Ask Me Slot", BGRE, "d9476193be84830ee6e05b7ebe3df5e6"),
    "DS": ProviderProps("Dragoon Soft", BRED, "001e5786030e25f207e329ed2a820c5d"),
    "HSG": ProviderProps("Hacksaw Gaming", BBLU, "7b6c3cb2219792a230e1d022c6986cfc"),
    "AMEBA": ProviderProps("AMEBA Entertainment",BMAG, "9be642a0e1d8a3a7c5e015d09f08adfe"),
    "BTG": ProviderProps("BTG", BCYN, "7adfed5a9cd06a581eff167bfbadd630"),
    "MEGA": ProviderProps("MEGA Entertainment", BYEL, "40d155acff304e642252f253993b126e"),
    "DNA": ProviderProps("DNA Slot", BLGRY, "a035b23795134651bcd27a923b7453f9"),
    "WM": ProviderProps("World Match", BLRED, "f6823427a35f41b1a378ad050a676db8"),
    "FIVE": ProviderProps("5", BLGRE, "014e6a00b1ff714d5e5cd44064d16f48"),
    "NEXT": ProviderProps("Next Spin", BLMAG, "6ad041e11133876eda65b5f993a66d4f"),
    "RG": ProviderProps("Rich Game", BLYEL, "133480bdccbc68ca1bc4cea932a0e8b7"),
    "MAHA": ProviderProps("MAHA Gaming", BWHTE, "fb40ff7da5ca4a8cbd1383d7d89c5b0f"),
    "BT": ProviderProps("BT Gaming", BLCYN, "78eaafcc8f8e8bf4716e5dcb416c1abb"),
    # "JFF": ProviderProps("JFF", MAG, ""),
}

DEFAULT_PROVIDER_PROPS = ProviderProps("Jili", WHTE, "41786877e5b48c0f35948ec66abdc1bd")

URLS = [ "https://www.helpslot.win", "https://slimeserveahead.github.io/monitor" ]

API_CONFIG = {
    "host": "0.0.0.0",
    "port": 4444,
    "reload": True,
    "url": next((url for url in URLS if 'helpslot' in url), None),
    "refresh_interval": 1  # fast initial poll interval
}

API_URL = [ "http://localhost:8080", "https://api-jackpot.fly.dev", "http://172.16.0.149:8080" ]
# API_URL = [ "http://localhost:8080", "https://api-jackpot.fly.dev", "http://192.168.1.10:8080" ]
# API_URL = "https://api-jackpot.fly.dev"
VPS_IP = "66.241.124.83"

USER_AGENTS = [
    # Windows Chrome
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/114.0.5735.91 Safari/537.36",
    # Mac Chrome
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/605.1.15 (KHTML, like Gecko) "
    "Version/16.1 Safari/605.1.15",
    # Mobile Android Chrome
    "Mozilla/5.0 (Linux; Android 11; Pixel 5) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/113.0.0.0 Mobile Safari/537.36",
    # iPhone Safari
    "Mozilla/5.0 (iPhone; CPU iPhone OS 15_3 like Mac OS X) "
    "AppleWebKit/605.1.15 (KHTML, like Gecko) "
    "Version/15.3 Mobile/15E148 Safari/604.1"
]