# fly.toml app configuration file generated for my-api-sg on 2025-07-01T08:46:30+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-api-sg'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
