# fly.toml app configuration file generated for scatter-slots on 2025-06-30T17:47:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scatter-slots'
primary_region = 'sin'

[build]

[env]
  PORT = '4444'

[http_service]
  internal_port = 4444
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
